// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tracking.Context;

namespace Tracking.Migrations
{
    [DbContext(typeof(MainApplicationContext))]
    [Migration("20220326221039_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("Tracking.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Tracking.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 3, 26, 23, 10, 39, 388, DateTimeKind.Local).AddTicks(1481),
                            Email = "ps@example.com",
                            FirstName = "Patryk",
                            LastName = "Szwermer",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 3, 26, 23, 10, 39, 391, DateTimeKind.Local).AddTicks(3438),
                            Email = "ps@example.com",
                            FirstName = "Przemyslaw",
                            LastName = "sawicki",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 3, 26, 23, 10, 39, 391, DateTimeKind.Local).AddTicks(3464),
                            Email = "md@example.com",
                            FirstName = "Marcin",
                            LastName = "Dabrowski",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 3, 26, 23, 10, 39, 391, DateTimeKind.Local).AddTicks(3468),
                            Email = "pk@example.com",
                            FirstName = "Piotr",
                            LastName = "Katny",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 3, 26, 23, 10, 39, 391, DateTimeKind.Local).AddTicks(3471),
                            Email = "md@example.com",
                            FirstName = "Marcin",
                            LastName = "Dudzic",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 3, 26, 23, 10, 39, 391, DateTimeKind.Local).AddTicks(3477),
                            Email = "mk@example.com",
                            FirstName = "Maciej",
                            LastName = "Krakowiak",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2022, 3, 26, 23, 10, 39, 391, DateTimeKind.Local).AddTicks(3479),
                            Email = "jk@example.com",
                            FirstName = "Jakub",
                            LastName = "Nowikowski",
                            PhoneNumber = ""
                        });
                });

            modelBuilder.Entity("Tracking.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tracking.Models.Event", b =>
                {
                    b.HasOne("Tracking.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
